wire_cutter_controller1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: wire_cutter_joint1
    joint_speed: 5
    motor:
        id: 5
        init: 0
        min: 0
        max: 4095
