set(_CATKIN_CURRENT_PACKAGE "ros_kinfu")
set(ros_kinfu_MAINTAINER "qut <c.lehnert@qut.edu.au>")
set(ros_kinfu_DEPRECATED "")
set(ros_kinfu_VERSION "0.0.0")
set(ros_kinfu_BUILD_DEPENDS "geometry_msgs" "image_transport" "message_filters" "roscpp" "sensor_msgs" "std_msgs" "tf" "cv_bridge" "pcl_ros" "pcl_ros" "eigen_conversions" "tf_conversions")
set(ros_kinfu_RUN_DEPENDS "geometry_msgs" "image_transport" "message_filters" "roscpp" "sensor_msgs" "std_msgs" "tf" "cv_bridge" "pcl_ros" "eigen_conversions" "tf_conversions")
set(ros_kinfu_BUILDTOOL_DEPENDS "catkin")